### ISSUE TITLE
Missing File for Matlab

### ISSUE THREAD

**Issue by chkone** [mstaib/stochastic-barycenter-code#1]
Hello,

The dataset in *.h5 format is missing (sampler_full.h5).
In skin_wasp_compare.m:
true_dist = h5read('cpp/sampler_full.h5', '/sampler_1000');

Cheers

**Comment by mstaib** [comment]
Hello, just noticed your question -- the sampler_full.h5 should be generated by the cpp code, as long as you run it with the -f (or -fullsampler) flag. The idea is to run the cpp code to generate experimental data, and then subsequently evaluate the results with the matlab scripts
